const planData={starter:{name:'Basic Starter',principal:245,spouse:215,child:150,summary:'An affordable entry-level option for essential everyday healthcare support.',benefits:[['GP + medication','3 visits'],['OTC / Pharmacy','M750 per annum'],['Specialist & acute medication','Subject to plan rules'],['Basic pathology','Referral and authorisation apply'],['Basic radiology','X-rays and ultrasounds subject to rules'],['Additional benefits','See policy schedule for applicable limits']]},saver:{name:'Basic Saver',principal:455,spouse:345,child:270,summary:'A stronger everyday medical aid option with broader benefit limits.',benefits:[['GP + medication','4 visits'],['OTC / Pharmacy','M750 per annum'],['Basic pathology','Referral and authorisation apply'],['Basic radiology','X-rays and ultrasounds subject to rules'],['Maternity / Dentistry','Applicable plan limits'],['Basic optometry','Applicable plan limits']]},plus:{name:'Basic Plus',principal:835,spouse:515,child:400,summary:'The most comprehensive of the three published low-cost medical aid options.',benefits:[['GP + medication','5 visits'],['OTC / Pharmacy','M1,000 per annum'],['Basic pathology','Enhanced plan limits'],['Basic radiology','X-rays and ultrasounds subject to rules'],['Maternity / Dentistry','Applicable plan limits'],['Basic optometry','Applicable plan limits']]}};
const partials={shell:'partials/shell.html',home:'partials/home.html',services:'partials/services.html',plans:'partials/plans.html',cash:'partials/cash.html',contact:'partials/contact.html',footer:'partials/footer.html',controls:'partials/controls.html'};
async function loadPart(id,url){const r=await fetch(url+'?v=3',{cache:'no-cache'});if(!r.ok)throw new Error(url+' '+r.status);document.getElementById(id).innerHTML=await r.text()}
async function boot(){try{await Promise.all(Object.entries(partials).map(([id,url])=>loadPart(id,url)));document.getElementById('loading').remove();initSite()}catch(e){console.error(e);document.getElementById('loading').innerHTML='<strong>Unable to load the demonstration.</strong><br>Please refresh the page.'}}
function initSite(){
 const planName=document.getElementById('planName'),planSummary=document.getElementById('planSummary'),principalPrice=document.getElementById('principalPrice'),spousePrice=document.getElementById('spousePrice'),childPrice=document.getElementById('childPrice'),benefitGrid=document.getElementById('benefitGrid'),qPlan=document.getElementById('qPlan'),qSpouse=document.getElementById('qSpouse'),qChildren=document.getElementById('qChildren'),estimateValue=document.getElementById('estimateValue'),estimateBreakdown=document.getElementById('estimateBreakdown'),waQuote=document.getElementById('waQuote'),modal=document.getElementById('quoteModal'),closeQuote=document.getElementById('closeQuote'),waMain=document.getElementById('waMain');
 const money=v=>'M'+Number(v).toLocaleString('en-US');
 function updateEstimate(){const p=planData[qPlan.value],spouse=Number(qSpouse.value),children=Number(qChildren.value),total=p.principal+spouse*p.spouse+children*p.child;estimateValue.textContent=money(total);const parts=['1 principal'];if(spouse)parts.push('1 spouse');if(children)parts.push(children+' child'+(children===1?'':'ren'));estimateBreakdown.textContent=p.name+' • '+parts.join(' • ');const msg=`Hello Guardrisk, I would like a medical aid quotation. Plan: ${p.name}. Family: ${parts.join(', ')}. Estimated base premium: ${money(total)} per month.`;waQuote.href='https://wa.me/26662720488?text='+encodeURIComponent(msg);waQuote.target='_blank';waQuote.rel='noopener'}
 function setPlan(key){const p=planData[key];planName.textContent=p.name;planSummary.textContent=p.summary;principalPrice.textContent=money(p.principal)+' / month';spousePrice.textContent=money(p.spouse)+' / month';childPrice.textContent=money(p.child)+' / month';benefitGrid.innerHTML=p.benefits.map(([a,b])=>`<div class="benefit"><b>${a}</b><small>${b}</small></div>`).join('');document.querySelectorAll('.plan-tab').forEach(btn=>{const active=btn.dataset.plan===key;btn.classList.toggle('active',active);btn.setAttribute('aria-selected',active?'true':'false')});qPlan.value=key;updateEstimate()}
 document.querySelectorAll('.plan-tab').forEach(btn=>btn.addEventListener('click',()=>setPlan(btn.dataset.plan)));
 function openQuote(){modal.hidden=false;modal.setAttribute('aria-hidden','false');document.body.style.overflow='hidden';updateEstimate();setTimeout(()=>closeQuote.focus(),0)}
 function closeModal(){modal.hidden=true;modal.setAttribute('aria-hidden','true');document.body.style.overflow=''}
 document.querySelectorAll('[data-quote]').forEach(el=>el.addEventListener('click',openQuote));closeQuote.addEventListener('click',closeModal);modal.addEventListener('click',e=>{if(e.target===modal)closeModal()});document.addEventListener('keydown',e=>{if(e.key==='Escape'&&!modal.hidden)closeModal()});[qPlan,qSpouse,qChildren].forEach(el=>el.addEventListener('change',updateEstimate));
 waMain.href='https://wa.me/26662720488?text='+encodeURIComponent('Hello Guardrisk, I would like more information.');waMain.target='_blank';waMain.rel='noopener';setPlan('starter')
}
document.addEventListener('DOMContentLoaded',boot);
